### ISSUE TITLE
base_url should be base_uri

### ISSUE THREAD

**Issue by emilebourquin** [marceux/maropost#1]
In Maropost.php, 

`$this->client = new Client([
            'base_url' => "http://api.maropost.com/accounts/$acct/",`

should be

`$this->client = new Client([
            'base_uri' => "http://api.maropost.com/accounts/$acct/",`

Without the change, Guzzle is throwing exceptions like:

"cURL error 6: Could not resolve host: lists"

**Comment by emilebourquin** [comment]
The above is because the latest Guzzle (6.x) changed base_url to base_uri. Perhaps a more appropriate change would be to lock Guzzle to 5.x .

In composer.json, change

`"guzzlehttp/guzzle": "*"`

to

`"guzzlehttp/guzzle": "5.3.0"`

**Comment by benallfree** [comment]
FYI locking to Guzzle 5 will conflict with Laravel which uses G6.

**Comment by marceux** [comment]
@emilebourquin and @benallfree 

Let me know if this needs to be updated. I'm not actively maintaining this repo because I'm no longer working at the company that requires it, but I can investigate the matter.

**Comment by benallfree** [comment]
My pull request fixed it. If you want to make me an admin on this repo I'd be happy to maintain it. It's being used for a long term project and Maropost could really use some official PHP bindings.

**Comment by marceux** [comment]
kk; closing this and making you admin. Cheers.

**Comment by benallfree** [comment]
If you want, add benallfree as an admin, I'm working on it for a long term project.
